### ISSUE TITLE
Spawn Grief Issues after N's Magical Fix

### ISSUE THREAD

**Issue by ErkCurley** [PlanetBeast/Pitek-2.0#12]
Item Name: Diamond Chisel
Mod Name: Chisel
Item ID: 4997

Item Name: Obsidian Chisel
Mod Name: Chisel
Item ID: 7107

By-pass in spawn, can chisel blocks that are already placed

Item Name: Manna Blaster
Mod Name: Botania
Item ID: 4655

Manna Blaster with the bore lense can break blocks in a GP / Region

Item Name: Aer Imbued Fire
Mod Name: Thaumic Tinker
Item ID: 1535

Item Name: Aqua Imbued Fire
Mod Name: Thaumic Tinker
Item ID: 1534

Item Name: Ordo Imbued Fire
Mod Name: Thaumic Tinker
Item ID: 1543

Item Name: Perditio Imbued Fire
Mod Name: Thaumic Tinker
Item ID: 1519

Item Name: Terra Imbued Fire
Mod Name: Thaumic Tinker
Item ID: 1529

Item Name: Ignis Imbued Fire
Mod Name: Thaumic Tinker
Item ID: 1525

These are extremely dangerous :P

Item Name: Flamethrower
Mod Name: Mekanism
Item ID: 7108:1

Item Name: Block and Chain
Mod Name: Twilight Forrest
Item ID: 7128

Item Name: Zombie Scepter
Mod Name: Twilight Forrest
Item ID: 4893

PVP / Mytown bypass

**Comment by PlanetBeast** [comment]
Fixed in 2.0.15.05.09
