### ISSUE TITLE
waila/sphax bug

### ISSUE THREAD

**Issue by theBurningVoid** [PlanetBeast/Pitek-2.0#13]
first off i apologize if I did not post this bug correctly as this my first time using github for anything and I wanted to get this posted before forgetting. I just installed the pureBDcraft sphax and the PiTek sphax patch and I immediately noticed a bug involved with waila. When dark oak wood logs are oriented up and down like they are when a tree grows everything works fine but when the logs are oriented in the north/south or west/east directions waila shows the dark oak logs as acacia. A similar bug can be seen with spruce and birch only waila mistakenly show regular oak wood when those are oriented sideways. screen shots are, hopefully again github noob, posted below

![2015-05-17_17 57 33](https://cloud.githubusercontent.com/assets/12487960/7672632/6723188e-fcbe-11e4-81cc-c1c93911ff72.png)
![2015-05-17_17 57 34](https://cloud.githubusercontent.com/assets/12487960/7672637/672aa3c4-fcbe-11e4-85d1-e6d797abbae0.png)
![2015-05-17_17 57 37](https://cloud.githubusercontent.com/assets/12487960/7672634/67290e56-fcbe-11e4-9601-14576f1a8de0.png)
![2015-05-17_17 58 09](https://cloud.githubusercontent.com/assets/12487960/7672636/672a719c-fcbe-11e4-8dee-41b6a9999578.png)
![2015-05-17_17 58 10](https://cloud.githubusercontent.com/assets/12487960/7672635/672a0892-fcbe-11e4-9dd3-f6c3703aad68.png)
![2015-05-17_17 58 11](https://cloud.githubusercontent.com/assets/12487960/7672633/672766aa-fcbe-11e4-911e-b976e84acb81.png)

**Comment by PlanetBeast** [comment]
This is a known bug with [WAILA](https://bitbucket.org/ProfMobius/waila/issue/150/spruce-logs-mistaken-for-oak). Unfortunately can't do anything about it until a fix comes with the mod.
