### ISSUE TITLE
Digital Miner automatically reactivates

### ISSUE THREAD

**Issue by JadesMeister** [PlanetBeast/Pitek-2.0#2]
The Digital Miner from Mekanism reactivates automatically and unintentionally when the chunk it is loaded in is unloaded and reloaded. This includes players leaving the area and returning, and even a server reboot. It has catastrophic potential.

**Comment by Reddawg99** [comment]
Nothing I can fix, and the dev doesn't care, so don't use it near your house.

**Comment by JzJad** [comment]
Just dont leave it powered with the dictionary "*" ....
