### ISSUE TITLE
[Crash] Braking GC/w Atomic

### ISSUE THREAD

**Issue by JzJad** [PlanetBeast/Pitek-2.0#4]
Breaking GC machines with an Atomic crashes the server.

**Comment by PlanetBeast** [comment]
An atomic disassembler?

**Comment by JzJad** [comment]
That would be correct.

**Comment by PlanetBeast** [comment]
Fixed in Mek 8

**Comment by JzJad** [comment]
Was fixed with GC already. Forgot to close the issue.
