### ISSUE TITLE
Item ByPass

### ISSUE THREAD

**Issue by JadesMeister** [PlanetBeast/Pitek-2.0#6]
Hi, ErkCurley and I have discovered an item that can bypass protections:
 Item Name: Block and Chain
Mod Name: Twilight Forest
Item ID: 7128

Item Name: Block of Annihilation
Mod Name: Twilight Forest
Item ID: 7110

The behavior of the item can break protected blocks.

**Comment by PlanetBeast** [comment]
See Issue #12
