### ISSUE TITLE
GP / Region protection bypass

### ISSUE THREAD

**Issue by ErkCurley** [PlanetBeast/Pitek-2.0#8]
Item Name: Crumble Horn
Mod Name: Twilight Forest
Item ID: 4947

Item Name: Chisel
Mod Name: Chisel
Item ID: 4996

Item Name: Diamond Chisel
Mod Name: Chisel
Item ID: 4997

Item Name: Obsidian Chisel
Mod Name: Chisel
Item ID: 7107

By-pass in spawn, can chisel blocks that are already placed

Every wrench / crowbar / hammer in the modpack can rotate stairs in the protected spawn area.

Item Name: Crane Backpack
Mod Name: Open Blocks
Item ID: 5671

GP / Region by-pass

Item Name: Manna Blaster
Mod Name: Botania
Item ID: 4655

Manna Blaster with the bore lense can break blocks in a GP / Region

Item Name: Smashing Rock
Mod Name: Chisel 
Item ID: 4999

By-pass Spawn protection

All florbs can be thrown in spawn and they DO spawn their content liquids

Item Name: Moonworm Queen
Mod Name: Twilight Forest
Item ID: 4949

Can shoot worms into spawn region

Item Name: Aer Imbued Fire
Mod Name: Thaumic Tinker
Item ID: 1535

Item Name: Aqua Imbued Fire
Mod Name: Thaumic Tinker
Item ID: 1534

Item Name: Ordo Imbued Fire
Mod Name: Thaumic Tinker
Item ID: 1543

Item Name: Perditio Imbued Fire
Mod Name: Thaumic Tinker
Item ID: 1519

Item Name: Terra Imbued Fire
Mod Name: Thaumic Tinker
Item ID: 1529

Item Name: Ignis Imbued Fire
Mod Name: Thaumic Tinker
Item ID: 1525

These are extremely dangerous :P

Item Name: Flamethrower
Mod Name: Mekanism
Item ID: 7108:1

**Comment by PlanetBeast** [comment]
Fixed in 2.0.15.05.09
